/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package az.edu.ada.wm2;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("This app should have a greeting", classUnderTest.getGreeting());
    }
}
