/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package az.edu.ada.wm2;

/**
 * @author nsadili
 */
public class App {
    /**
     * This is a sample greeting methods
     * @return
     */
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
