/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package az.edu.ada.wm2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    /**
     * This is a test javadoc example
     */
    private void test(){

    }
}
